CREATE TABLE REGISTRY(
	id UUID PRIMARY KEY,
	navegador VARCHAR(50) NOT NULL,
	horario_acesso DATE NOT NULL,
	idade INTEGER NOT NULL,
	tipo_aparelho INTEGER NOT NULL,
	origem_acesso INTEGER NOT NULL
);